### PR TITLE
This here PR will, when approved, add Jackson's biographical info.

### PR DESCRIPTION
**Pull request by abstractionjackson**
here's my bio

### CODE REVIEW

**Review by JulieBoberg — CHANGES_REQUESTED** [review]
Please change commit message to what was done, not what you plan on doing. This makes it easier if anything has to be reverted in the future. The current commit message implies that you didn't add the third row. If it can't be fixed let me know, but I would like to keep our commit messages as communicative as possible.
 Thanks Jackson!

**Comment by abstractionjackson** [comment]
The verb tense is meant to describe the branch commit after an approved PR.
A more verbose message would read, "This commit, when merged, will add
feature X." That's the style I was taught and have been using, and I think
it makes grammatical sense. What are your thoughts?

**Comment by JulieBoberg** [comment]
Please write out the more verbose version or write it out similar to 'Added a third row'. Whenever I see your commit messages they sound like issues that need to be solved, not what was actually fixed. Obviously it shouldn't be a problem for a basic thing like a bio card but in the future if you work on other features it could cause a miscommunication. Thank you.

**Review by abstractionjackson — COMMENTED** [review]
this commit refactors the message for clarity

**Review by JulieBoberg — APPROVED** [review]

**Comment by JulieBoberg** [comment]
Thanks Jackson!

**Pull request merged**
